---
- name: Update the APT package cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install KVM and dependencies
  ansible.builtin.apt:
    name:
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
      - virt-manager
      - tigervnc-viewer
      - terraform
      - git
      - make
      - gcc
      - libvirt-dev
      - golang  
    state: present

- name: Ensure libvirtd qemu security is disabled
  ansible.builtin.lineinfile:
    path: /etc/libvirt/qemu.conf
    line: "security_driver = [ \"none\" ]"
    state: present

- name: Ensure libvirtd service is enabled and started
  ansible.builtin.systemd:
    name: libvirtd
    enabled: yes
    state: started

- name: Add current user to libvirt and kvm groups
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    groups: libvirt,kvm
    append: yes

- name: Print message to log out and back in
  ansible.builtin.debug:
    msg: "Installation complete. Please log out and log back in to apply group changes."

- name: Clone the terraform-provider-libvirt repository
  become: no
  git:
    repo: https://github.com/dmacvicar/terraform-provider-libvirt.git
    dest: /tmp/terraform-provider-libvirt
    version: main

- name: Change directory and build the provider
  command: make
  become: no
  args:
    chdir: /tmp/terraform-provider-libvirt

- name: Run make install
  command: make install
  become: no
  args:
    chdir: /tmp/terraform-provider-libvirt