- name: Define a new network
  virt_net:
    command: define
    name: br0-default
    xml: |
      <network>
        <name>{{ kvm_host.libvirt_bridge}}</name>
        <forward mode='bridge'/>
        <bridge name='br0'/>
      </network>
 
- name: Start the network
  virt_net:
    command: start
    name: "{{ kvm_host.libvirt_bridge }}"

- name: Set autostart command as a fact
  set_fact:
    autostart_command: "virsh net-autostart {{ kvm_host.libvirt_bridge }}"

- name: Run the autostart command
  command: "{{ autostart_command }}"
